### ISSUE TITLE
Scan van QR-code in OSX-wallet met Android wallet geeft foutmelding

### ISSUE THREAD

**Issue by gerritoerlemans** [Electronic-Gulden-Foundation/egulden#2]
De melding was "Kan input niet classificeren". Er kwam wel een public key in beeld waarvan de eerste drie en laatste drie karakters klopten. De fout herhaalde zich na het genereren van een nieuwe key;
Uiteindelijk bleek de key wel valide zodat de Android interpretatie van de key niet correct lijkt.

**Comment by AmazingDreams** [comment]
Ik geloof dat dit te maken heeft met egulden:<pubkey> vs e-gulden:<pubkey>. Ik vind dat het allebei ondersteund moet worden.
