### ISSUE TITLE
De wallet geeft in het debugscherm regelmatig een te hoog geschat aantal blokken

### ISSUE THREAD

**Issue by gerritoerlemans** [Electronic-Gulden-Foundation/egulden#3]
Dit gaat gepaard met een onterechte melding in het hoofdscherm "Niet gesynchroniseerd"
Op zich verstoord dit niet het functioneren van de wallet.
Het is vooral hinderlijk als de wallet voor het eerst in gebruik genomen wordt omdat je dan niet weet of de volledige blokchain is ingeladen.

**Comment by AmazingDreams** [comment]
Dit is een bekend probleem.

Komt doordat de chains gemixed zijn. Oorspronkelijke ontwikkelaars hebben (niet) gekozen voor deze waardes. Kan mogelijk aangepast worden.

https://github.com/Electronic-Gulden-Foundation/egulden/blob/master/src/main.cpp#L3165

**Comment by AmazingDreams** [comment]
Gefixed in commit dd71a3e3c36ac84c0559b6d682837e48f335a4dd
