### ISSUE TITLE
OSX software-installer geeft een melding dat de applicatie niet de standaard procedure volgt

### ISSUE THREAD

**Issue by gerritoerlemans** [Electronic-Gulden-Foundation/egulden#4]
Ik heb de precieze melding niet bij de hand, maar er is een handmatige ingreep nodig om de installatie  voort te zetten. Misschien kan dit gepolijst worden.

**Comment by AmazingDreams** [comment]
Dit vind ik een beetje vaag. Het is zo'n klik-en-sleep-naar-applicaties installer
