### ISSUE TITLE
fout bij het laden van blokkendatabase

### ISSUE THREAD

**Issue by jordol** [Electronic-Gulden-Foundation/egulden#5]
Bij het draaien van egulden-qt versie 1.4.3 geeft hij de melding fout bij het laden van de blokken database.
Hoe kan ik dit oplossen?

**Comment by AmazingDreams** [comment]
Gaat de wallet niet herindexeren als je daar op OK drukt?

Je kunt een herindex forceren door de wallet te starten met `-reindex=1` command line parameter.
