### ISSUE TITLE
peer magic

### ISSUE THREAD

**Issue by jdamhost** [Electronic-Gulden-Foundation/egulden#6]
Hi I have added egulden to my pool but it is asking for the peer magic .. I have search online with no avail are you able to provide this?

**Comment by AmazingDreams** [comment]
Sorry for the late reply. I've been rather busy lately.

`pchMessageStart` can be found [here](https://github.com/Electronic-Gulden-Foundation/egulden/blob/master/src/chainparams.cpp#L114) 

`fbc0b6db`

Let me know if you need anything else. By the way what is your pool url? We can add it to the list of pools.
